def explain(features, markov=0.0, rf=0.0, graph=0.0, ring=0.0):
    """
    Transparent reason-code explanation for the prototype.

    These are contribution heuristics, not SHAP values. Real SHAP values
    should be generated by the trained RF model before publication.
    """
    reasons = []

    def add(name, value, threshold, weight):
        if value >= threshold:
            reasons.append({
                "feature": name,
                "value": float(value),
                "contribution": round(min(1.0, value * weight), 4),
            })

    add("markov_risk", markov, 0.50, 0.25)
    add("rf_probability", rf, 0.50, 0.35)
    add("graph_risk", graph, 0.50, 0.25)
    add("ring_signal", ring, 0.50, 0.05)

    for key, value in features.items():
        if isinstance(value, (int, float)):
            if "counterpart" in key and value >= 8:
                reasons.append({
                    "feature": key,
                    "value": float(value),
                    "contribution": 0.10,
                })
            elif "count" in key and value >= 20:
                reasons.append({
                    "feature": key,
                    "value": float(value),
                    "contribution": 0.10,
                })

    reasons.sort(key=lambda x: x["contribution"], reverse=True)
    return reasons[:8]
